### ISSUE TITLE
Budgets to Replicate this ReConcile Experiments

### ISSUE THREAD

**Issue by weiyueli7** [dinobby/ReConcile#4]
Dear authors, we really appreciate your work and would like to replicate it as part of our capstone project. We wonder what's the computation budgets for you to run all experiments. What GPU did you use and how many GPU hours were spent? How much money is needed for both GPT and Claude APIs? Thanks!

**Comment by dinobby** [comment]
Hello, thank you for your interest in our work! In this project, most of the experiments are done using API-based models, e.g., ChatGPT, GPT4, Claude and Bard. In these experiments, none of the GPUs has been used. For open-sourced models like Llama2 and DeepSeekMath, we use a single A6000 48G for inference. On 100 test samples, it takes less than 10 minutes. To estimate the budget, please refer to the following table:

| Dataset | Avg. # Token  |
|---------|--------|
| StrategyQA | 924.5 |
| GSM8K     | 642.3 |

Since the price for each API varies over time, we provide the average token counts including input and output for an estimation. Please let me know if this answers your question! Thank you.
